import { StyleSheet } from 'react-native';

const MORADO = '#3d263a';
const SALMON = '#ff9e71';

export default StyleSheet.create({
  container: { flex: 1, backgroundColor: '#fdf8f6' },
  header: {
    backgroundColor: MORADO,
    paddingTop: 50,
    paddingBottom: 20,
    paddingHorizontal: 20,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  headerTitle: { fontSize: 18, fontWeight: '700', color: '#fff', flex: 1 },
  backBtn: { padding: 4 },
  backTexto: { fontSize: 14, color: SALMON, fontWeight: '600' },
  scroll: { flex: 1 },
  scrollContent: { padding: 16, paddingBottom: 40 },
  label: {
    fontSize: 12,
    fontWeight: '700',
    color: MORADO,
    marginBottom: 6,
    marginTop: 14,
    letterSpacing: 0.3,
  },
  input: {
    backgroundColor: '#fff',
    borderWidth: 1.5,
    borderColor: '#e8d8e4',
    borderRadius: 8,
    padding: 12,
    fontSize: 14,
    color: MORADO,
  },
  // Preguntas
  preguntaCard: {
    backgroundColor: '#fff',
    borderRadius: 12,
    padding: 14,
    marginBottom: 10,
    borderWidth: 0.5,
    borderColor: '#e8d8e4',
    shadowColor: MORADO,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  preguntaNum: { fontSize: 11, color: SALMON, fontWeight: '700', marginBottom: 6 },
  preguntaInput: {
    backgroundColor: '#fdf8f6',
    borderWidth: 1,
    borderColor: '#e8d8e4',
    borderRadius: 8,
    padding: 10,
    fontSize: 13,
    color: MORADO,
    marginBottom: 8,
  },
  tipoRow: { flexDirection: 'row', gap: 6, flexWrap: 'wrap', marginBottom: 8 },
  tipoBtn: {
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#e8d8e4',
    backgroundColor: '#fdf8f6',
  },
  tipoBtnActivo: { backgroundColor: MORADO, borderColor: MORADO },
  tipoBtnTexto: { fontSize: 11, color: '#7a5f76' },
  tipoBtnTextoActivo: { color: '#fff', fontWeight: '600' },
  fotoToggle: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginTop: 4,
  },
  fotoToggleTexto: { fontSize: 12, color: '#7a5f76' },
  fotoToggleActivo: { color: MORADO, fontWeight: '600' },
  eliminarBtn: {
    alignSelf: 'flex-end',
    paddingHorizontal: 10,
    paddingVertical: 4,
    marginTop: 6,
  },
  eliminarTexto: { fontSize: 12, color: '#c4607a' },
  agregarPreguntaBtn: {
    borderWidth: 1.5,
    borderColor: SALMON,
    borderStyle: 'dashed',
    borderRadius: 12,
    padding: 14,
    alignItems: 'center',
    marginBottom: 16,
  },
  agregarPreguntaTexto: { fontSize: 14, color: SALMON, fontWeight: '600' },
  guardarBtn: {
    backgroundColor: MORADO,
    borderRadius: 12,
    padding: 15,
    alignItems: 'center',
    shadowColor: MORADO,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 4,
  },
  guardarBtnTexto: { color: '#fff', fontSize: 15, fontWeight: '700', letterSpacing: 0.5 },
});