import { StyleSheet, Platform } from 'react-native';

const MORADO  = '#3d263a';
const SALMON  = '#ff9e71';
const MEDIO   = '#6b3a52';
const BLANCO  = '#FFFFFF';
const GRIS    = '#8E8E93';
const BORDE   = '#EDE4E9';
const FONDO   = '#fdf8f6';

export default StyleSheet.create({
  hero: {
    alignItems: 'center',
    paddingBottom: 22,
    paddingTop: Platform.OS === 'ios' ? 70 : 60,
    backgroundColor: FONDO,
    overflow: 'hidden',
  },
  heroBg: {
    position: 'absolute',
    top: 0, left: 0, right: 0,
    height: 160,
    opacity: 0.14,
  },
  avatarWrap: {
    position: 'relative',
    marginBottom: 12,
  },
  avatarImg: {
    width: 84,
    height: 84,
    borderRadius: 42,
    borderWidth: 3,
    borderColor: BLANCO,
  },
  avatarPlaceholder: {
    width: 84,
    height: 84,
    borderRadius: 42,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 3,
    borderColor: BLANCO,
    shadowColor: MORADO,
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 3,
  },
  avatarLetra: {
    color: BLANCO,
    fontSize: 32,
    fontWeight: '800',
  },
  camaraBtn: {
    position: 'absolute',
    bottom: 0,
    right: 0,
    backgroundColor: BLANCO,
    borderRadius: 11,
    width: 26,
    height: 26,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 4,
    elevation: 3,
  },
  nombre: {
    fontSize: 20,
    fontWeight: '700',
    color: MORADO,
    marginTop: 4,
  },
  email: {
    fontSize: 12,
    color: GRIS,
    marginTop: 2,
    marginBottom: 10,
  },
  rolPill: {
    paddingHorizontal: 16,
    paddingVertical: 5,
    borderRadius: 20,
    borderWidth: 1,
    backgroundColor: 'rgba(255,158,113,0.14)',
    borderColor: 'rgba(255,158,113,0.35)',
  },
  rolTexto: {
    fontSize: 12,
    fontWeight: '700',
    color: '#cc6a3a',
  },
  infoRow: {
    flexDirection: 'row',
    gap: 12,
    paddingHorizontal: 16,
    marginTop: 18,
    marginBottom: 14,
  },
  infoCard: {
    flex: 1,
    backgroundColor: BLANCO,
    borderRadius: 18,
    padding: 16,
    alignItems: 'center',
    shadowColor: MORADO,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 10,
    elevation: 3,
  },
  infoNum: {
    fontSize: 22,
    fontWeight: '800',
    color: MORADO,
  },
  infoLabel: {
    fontSize: 10,
    color: GRIS,
    textAlign: 'center',
    marginTop: 4,
    lineHeight: 14,
    fontWeight: '500',
  },
  sucursalCard: {
    backgroundColor: BLANCO,
    borderRadius: 18,
    padding: 14,
    flexDirection: 'row',
    alignItems: 'center',
    marginHorizontal: 16,
    marginBottom: 18,
    borderLeftWidth: 3,
    borderLeftColor: SALMON,
    shadowColor: MORADO,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 10,
    elevation: 3,
  },
  sucursalNombre: {
    fontSize: 14,
    fontWeight: '700',
    color: MORADO,
  },
  sucursalDir: {
    fontSize: 12,
    color: GRIS,
    marginTop: 2,
  },
  tabsRow: {
    flexDirection: 'row',
    borderBottomWidth: 1,
    borderBottomColor: BORDE,
    marginHorizontal: 16,
    marginBottom: 14,
  },
  tabBtn: {
    flex: 1,
    paddingVertical: 12,
    alignItems: 'center',
    borderBottomWidth: 2,
    borderBottomColor: 'transparent',
  },
  tabLabel: {
    fontSize: 13,
    color: GRIS,
    fontWeight: '500',
  },
  historialCard: {
    backgroundColor: BLANCO,
    borderRadius: 18,
    padding: 14,
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginBottom: 10,
    shadowColor: MORADO,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 10,
    elevation: 3,
  },
  historialDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
    marginRight: 10,
    marginTop: 4,
  },
  historialTitulo: {
    fontSize: 14,
    fontWeight: '700',
    color: MORADO,
  },
  historialFecha: {
    fontSize: 11,
    color: GRIS,
    marginTop: 2,
  },
  historialSub: {
    fontSize: 11,
    color: GRIS,
    marginTop: 2,
    lineHeight: 16,
  },
  checkBadge: {
    width: 28,
    height: 28,
    borderRadius: 14,
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: 8,
  },
  vacio: {
    textAlign: 'center',
    color: GRIS,
    fontSize: 13,
    paddingVertical: 30,
  },
  logoutBtn: {
    margin: 16,
    marginTop: 24,
    backgroundColor: 'rgba(255,59,48,0.08)',
    borderRadius: 16,
    padding: 16,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255,59,48,0.2)',
  },
  logoutTexto: {
    color: '#FF3B30',
    fontWeight: '700',
    fontSize: 14,
  },
});