import { StyleSheet, Platform } from 'react-native';

const MORADO = '#3d263a';
const SALMON = '#ff9e71';
const MEDIO = '#6b3a52';

export default StyleSheet.create({
  container: { flex: 1, backgroundColor: '#fdf8f6' },
  header: {
    paddingTop: Platform.OS === 'ios' ? 54 : 40,
    paddingBottom: 22,
    paddingHorizontal: 20,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    backgroundColor: MORADO,
    borderBottomLeftRadius: 22,
    borderBottomRightRadius: 22,
  },
  sucursal: { fontSize: 21, fontWeight: '700', color: '#fff', lineHeight: 26 },
  fecha: { fontSize: 12, color: 'rgba(255,255,255,0.55)', marginTop: 4, textTransform: 'capitalize' },
  gpsBadge: {
    backgroundColor: 'rgba(255,255,255,0.10)',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: 'rgba(255,158,113,0.5)',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
  },
  gpsText: { fontSize: 11, color: SALMON, fontWeight: '700', letterSpacing: 0.5 },
  rolBadge: {
    paddingVertical: 10,
    paddingHorizontal: 16,
    alignItems: 'center',
  },
  rolCocina: { backgroundColor: MEDIO },
  rolUsuario: { backgroundColor: '#5a3248' },
  rolTexto: {
    fontSize: 13,
    fontWeight: '700',
    color: SALMON,
    textTransform: 'uppercase',
    letterSpacing: 1,
  },
  progressBar: { height: 4, backgroundColor: 'rgba(61,38,58,0.15)' },
  progressFill: {
    height: '100%',
    backgroundColor: SALMON,
  },
  scroll: { flex: 1 },
  scrollContent: { padding: 14, paddingBottom: 40 },
  bloqueTitle: {
    fontSize: 12,
    fontWeight: '800',
    color: SALMON,
    textTransform: 'uppercase',
    letterSpacing: 1,
    marginBottom: 8,
    marginTop: 16,
    borderLeftWidth: 3,
    borderLeftColor: SALMON,
    paddingLeft: 8,
  },
  card: {
    backgroundColor: '#fff',
    borderRadius: 16,
    padding: 16,
    marginBottom: 10,
    shadowColor: MORADO,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 10,
    elevation: 3,
  },
  numPregunta: {
    fontSize: 11,
    color: SALMON,
    fontWeight: '700',
    marginBottom: 6,
  },
  textoPregunta: {
    fontSize: 14,
    fontWeight: '600',
    color: MORADO,
    marginBottom: 12,
    lineHeight: 20,
  },
  opcion: {
    backgroundColor: '#fdf8f6',
    borderWidth: 1.5,
    borderColor: '#e8d8e4',
    borderRadius: 10,
    padding: 10,
    marginBottom: 6,
  },
  opcionSeleccionada: {
    borderColor: MORADO,
    backgroundColor: '#f3eef2',
  },
  opcionTexto: { fontSize: 13, color: '#5a3248' },
  opcionTextoSeleccionado: { fontWeight: '700', color: MORADO },
  textInput: {
    backgroundColor: '#fdf8f6',
    borderWidth: 1.5,
    borderColor: '#e8d8e4',
    borderRadius: 10,
    padding: 10,
    fontSize: 13,
    color: MORADO,
    minHeight: 80,
    textAlignVertical: 'top',
  },
  fotoBtn: {
    marginTop: 10,
    borderWidth: 1.5,
    borderColor: '#e8d8e4',
    borderStyle: 'dashed',
    borderRadius: 10,
    padding: 14,
    alignItems: 'center',
    backgroundColor: '#fdf8f6',
  },
  fotoBtnDone: {
    borderStyle: 'solid',
    borderColor: '#34C759',
    backgroundColor: '#F0FFF4',
  },
  fotoBtnTexto: { fontSize: 13, color: '#7a5f76' },
  fotoBtnTextoDone: { color: '#34C759', fontWeight: '600' },
  obligatorioTexto: {
    fontSize: 11,
    color: '#c4607a',
    marginTop: 6,
    fontStyle: 'italic',
  },
  submitBtn: {
    backgroundColor: MORADO,
    borderRadius: 12,
    padding: 15,
    alignItems: 'center',
    marginTop: 16,
    shadowColor: MORADO,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 4,
  },
  submitBtnDisabled: {
    backgroundColor: '#b49cb0',
    elevation: 0,
    shadowOpacity: 0,
  },
  submitBtnTexto: { color: '#fff', fontSize: 15, fontWeight: '700', letterSpacing: 0.5 },
  centerScreen: {
    flex: 1,
    backgroundColor: '#fdf8f6',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 32,
  },
  detectingTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: MORADO,
    marginTop: 16,
    textAlign: 'center',
  },
  detectingSubtitle: {
    fontSize: 13,
    color: '#7a5f76',
    textAlign: 'center',
    marginTop: 8,
  },
  blockedTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: MORADO,
    marginTop: 12,
    marginBottom: 8,
  },
  blockedMessage: {
    fontSize: 13,
    color: '#7a5f76',
    textAlign: 'center',
    lineHeight: 20,
  },
  retryButton: {
    backgroundColor: MORADO,
    borderRadius: 10,
    paddingHorizontal: 28,
    paddingVertical: 12,
    marginTop: 20,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  retryButtonText: { fontSize: 14, color: '#fff', fontWeight: '600' },
  reporteEncuestaBtn: {
    backgroundColor: '#f3eef2',
    borderRadius: 12,
    padding: 13,
    alignItems: 'center',
    marginBottom: 10,
    borderWidth: 1,
    borderColor: '#e8d8e4',
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 8,
  },
  reporteEncuestaBtnTexto: {
    fontSize: 14,
    color: '#6b3a52',
    fontWeight: '600',
  },
  volverBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: 'rgba(255,255,255,0.12)',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 20,
  },
  volverBtnTexto: {
    fontWeight: '600',
    fontSize: 13,
  },
});